apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: aegisai
data:
  # Application Settings
  DOCKER: "True"
  DEBUG: "False"
  AUTH_ENVIRONMENT: "local"

  # Storage Settings
  STORAGE_ROOT: "/app/shared-storage"
  RAW_DIR: "/app/shared-storage/raw"
  PROCESSED_DIR: "/app/shared-storage/processed"
  TRANSCODED_DIR: "/app/shared-storage/transcoded"

  # AWS S3 Buckets
  USE_AWS: "True"
  RAW_DIR_AWS: "aegisai-raw-danielzorov"
  PROCESSED_DIR_AWS: "aegisai-processed-danielzorov"
  TRANSCODED_DIR_AWS: "aegisai-transcoded-danielzorov"

  # Service URLs
  USE_ORCHESTRATOR: "True"
  ORCHESTRATOR_URL: "http://workflow-orchestrator:9000/jobs"

  # Redis Settings
  TEST_REDIS_URL: "redis://redis:6379/2"
  USE_REDIS_PUBLISH: "True"
  USE_REDIS_LISTENER: "true"

  # Database Settings
  USE_SHARED_LIB: "True"
  DB_NAME: "aegisai_db"
  DB_USER: "postgres_user"
  DB_HOST: "postgres"
  DB_PORT: "5432"

  # AI Service Settings
  LANGSMITH_TRACING: "true"
  LANGSMITH_PROJECT: "custom-llm"
  LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  INDEX_NAME: "custom-index"
  INDEX2_NAME: "langchain-docs-2025"
